using UnityEngine;
using UnityEngine.UI;
using UnityEngine.EventSystems;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

public partial class PulseLobby {
 [Serializable] class LobbyReport {public bool success;public int checks,buttonRaycasts,animatedModeVictories;public string captureMethod="Actual Unity 3D cameras, postprocessing and native Canvas rendered offscreen";public string[] failures;}
 readonly List<string> lobbyFailures=new();int lobbyChecks,lobbyRays,modeWins;
 void VerifyExclusiveScreen(bool menu){
  var contact=stage.spirit.Find("Soft contact radiance");
  Verify(contact&&contact.GetComponent<Renderer>().sharedMaterial.shader.name=="Pulse/CinematicContact","Skin replaced the contact-light shader with a model atlas");
  var huds=FindObjectsByType<CampaignHUD>(FindObjectsInactive.Include,FindObjectsSortMode.None).Where(h=>h.gameObject.scene==game.gameObject.scene).ToArray();
  Verify(canvas.isActiveAndEnabled==menu&&stage.view.isActiveAndEnabled==menu&&game.gameCamera.isActiveAndEnabled!=menu,"UI / world cameras belong to different screens");
  Verify(menu?huds.All(h=>!h.gameObject.activeInHierarchy):huds.Count(h=>h.gameObject.activeInHierarchy)==1,"Gameplay HUD root remains active in menu / duplicate gameplay HUD");
  var cameras=Camera.allCameras.Where(c=>c.targetTexture==null&&c.gameObject.scene==game.gameObject.scene).ToArray();
  Verify(cameras.Length==1&&cameras[0]==(menu?stage.view:game.gameCamera),"Multiple world cameras rendering into the same screen");
  var canvases=FindObjectsByType<Canvas>(FindObjectsSortMode.None).Where(c=>c.isActiveAndEnabled&&c.gameObject.scene==game.gameObject.scene).ToArray();
  Verify(canvases.Length==1&&canvases[0]==(menu?canvas:huds.First(h=>h.gameObject.activeInHierarchy).GetComponent<Canvas>()),"Another Canvas is drawing over the active screen");
  Verify(!game.editableBoard.gameObject.activeInHierarchy,"Editable preview board leaks into runtime");
  Verify((game.gameCamera.cullingMask&(1<<28))==0&&stage.view.cullingMask==(1<<28),"Menu and gameplay camera layers overlap");
  if(menu){foreach(var y in new[]{60,915}){var results=new List<RaycastResult>();EventSystem.current.RaycastAll(new PointerEventData(EventSystem.current){position=Point(270,y)},results);Verify(results.All(r=>!r.gameObject.GetComponentInParent<CampaignHUD>()),"Hidden gameplay UI intercepts menu clicks");}}
 }
 IEnumerator VerifyStalePresentation(){
  var source=FindObjectsByType<CampaignHUD>(FindObjectsInactive.Include,FindObjectsSortMode.None).First(h=>h.game==game);
  var duplicate=Instantiate(source.gameObject);duplicate.name="TEST • stale duplicate HUD";duplicate.SetActive(true);
  var nested=new GameObject("TEST • nested Canvas",typeof(RectTransform),typeof(Canvas));nested.transform.SetParent(duplicate.transform,false);nested.GetComponent<Canvas>().overrideSorting=true;
  source.gameObject.SetActive(true);source.GetComponent<Canvas>().enabled=true;
  game.gameCamera.enabled=true;game.editableBoard.gameObject.SetActive(true);stage.gameObject.SetActive(false);stage.view.cullingMask=0;
  game.RefreshPresentationHuds();RefreshPresentation();yield return null;VerifyExclusiveScreen(true);
  game.RequestUI(CampaignUICommand.Pause);Verify(!game.Paused,"Hidden gameplay action can pause the menu");
  Verify(CampaignHUD.Ensure(game)==source&&FindObjectsByType<CampaignHUD>(FindObjectsInactive.Include,FindObjectsSortMode.None).Length==2,"Ensure duplicated an inactive HUD");
  Hide();yield return null;VerifyExclusiveScreen(false);Open();yield return null;VerifyExclusiveScreen(true);
  Destroy(duplicate);yield return null;game.RefreshPresentationHuds();
  // Existing saved layouts must be cleaned, not just the freshly built template.
  var stale=Button(safeRoot,"Navigation • old bottom button",LobbyAction.Home,50,50,270,930);
  var staleMode=Button(safeRoot,"Old mode card",LobbyAction.Endless,50,50,270,830);
  UpgradeLayout();yield return null;Verify(!stale&&!staleMode,"Saved-scene UI migration did not remove old buttons");
  for(int i=0;i<3;i++){Hide();yield return null;VerifyExclusiveScreen(false);Open();yield return null;VerifyExclusiveScreen(true);}
 }
 void Verify(bool pass,string message){if(pass)lobbyChecks++;else{lobbyFailures.Add(message);Debug.LogError("LOBBY_CHECK_FAILED: "+message);}}
 LobbyButton FindButton(LobbyAction action,int value=0)=>canvas.GetComponentsInChildren<LobbyButton>().LastOrDefault(b=>b.action==action&&b.value==value&&b.gameObject.activeInHierarchy&&b.GetComponent<Button>().interactable);
 void Press(LobbyAction action,int value=0){var b=FindButton(action,value);Verify(b,"Missing live button "+action+" / "+value);if(!b)return;var p=new PointerEventData(EventSystem.current){button=PointerEventData.InputButton.Left};ExecuteEvents.Execute(b.gameObject,p,ExecuteEvents.pointerDownHandler);ExecuteEvents.Execute(b.gameObject,p,ExecuteEvents.pointerUpHandler);ExecuteEvents.Execute(b.gameObject,p,ExecuteEvents.pointerClickHandler);}
 void VerifyPageRays(){Canvas.ForceUpdateCanvases();var caster=canvas.GetComponent<GraphicRaycaster>();foreach(var b in canvas.GetComponentsInChildren<LobbyButton>()){if(!b.GetComponent<Button>().interactable||!b.gameObject.activeInHierarchy||Page!=""&&!b.transform.IsChildOf(popupRoot))continue;var rect=(RectTransform)b.transform;var pos=RectTransformUtility.WorldToScreenPoint(null,rect.TransformPoint(rect.rect.center));var hits=new List<RaycastResult>();caster.Raycast(new PointerEventData(EventSystem.current){position=pos},hits);Verify(pos.x>=0&&pos.x<=Screen.width&&pos.y>=0&&pos.y<=Screen.height,"Button outside screen "+b.name);bool hit=hits.Count>0&&hits[0].gameObject.GetComponentInParent<LobbyButton>()==b;Verify(hit,"Button covered by another graphic "+b.name+" -> "+string.Join(" / ",hits.Take(3).Select(h=>h.gameObject.name)));if(hit)lobbyRays++;}}
 public static Texture2D CaptureFrame(Camera camera,Canvas canvas,int width=0,int height=0){
  if(width<=0)width=Screen.width;if(height<=0)height=Screen.height;float scale=canvas.scaleFactor;
  var priorTarget=camera.targetTexture;var priorActive=RenderTexture.active;var mode=canvas.renderMode;var canvasCamera=canvas.worldCamera;float plane=canvas.planeDistance;
  var nodes=canvas.GetComponentsInChildren<Transform>(true);var layers=nodes.Select(n=>n.gameObject.layer).ToArray();var target=new RenderTexture(width,height,24,RenderTextureFormat.ARGB32,RenderTextureReadWrite.sRGB);var host=new GameObject("Lobby verification overlay camera");var overlay=host.AddComponent<Camera>();overlay.enabled=false;
  try{target.Create();camera.targetTexture=target;camera.Render();camera.targetTexture=priorTarget;overlay.targetTexture=target;overlay.clearFlags=CameraClearFlags.Depth;overlay.cullingMask=1<<31;overlay.orthographic=true;overlay.orthographicSize=5;overlay.nearClipPlane=.01f;overlay.farClipPlane=2;overlay.allowHDR=false;foreach(var node in nodes)node.gameObject.layer=31;canvas.renderMode=RenderMode.ScreenSpaceCamera;canvas.worldCamera=overlay;canvas.planeDistance=.5f;canvas.scaleFactor=scale*width/Screen.width;foreach(var graphic in canvas.GetComponentsInChildren<Graphic>(true))graphic.SetAllDirty();Canvas.ForceUpdateCanvases();overlay.Render();RenderTexture.active=target;var texture=new Texture2D(width,height,TextureFormat.RGB24,false);texture.ReadPixels(new Rect(0,0,width,height),0,0);texture.Apply();return texture;}
  finally{camera.targetTexture=priorTarget;RenderTexture.active=priorActive;canvas.renderMode=mode;canvas.worldCamera=canvasCamera;canvas.planeDistance=plane;canvas.scaleFactor=scale;foreach(var graphic in canvas.GetComponentsInChildren<Graphic>(true))graphic.SetAllDirty();for(int i=0;i<nodes.Length;i++)nodes[i].gameObject.layer=layers[i];Canvas.ForceUpdateCanvases();overlay.targetTexture=null;Destroy(host);target.Release();Destroy(target);}
 }
 IEnumerator Shot(string name){yield return new WaitForSeconds(.3f);yield return new WaitForEndOfFrame();var texture=CaptureFrame(stage.view,canvas);var pixels=texture.GetPixels32();Verify(pixels.Count(p=>p.r>20||p.g>20||p.b>20)>pixels.Length*.1f,"Empty menu render "+name);Verify(pixels.Count(p=>p.r>247&&p.g<12&&p.b>247)<pixels.Length*.006f,"Magenta shader error "+name);System.IO.File.WriteAllBytes(System.IO.Path.GetFullPath(Application.dataPath+"/../../"+name+".png"),ImageConversion.EncodeToPNG(texture));Destroy(texture);}
 public IEnumerator VerifyLobby(){
  string persisted=PlayerPrefs.GetString("PulseLobby.Profile.v1","");string savedProgress=PlayerPrefs.GetInt("PulseCampaign.Variety2.Current",1)+"/"+PlayerPrefs.GetInt("PulseCampaign.Variety2.Unlocked",1);var cameraPosition=game.gameCamera.transform.position;var cameraRotation=game.gameCamera.transform.rotation;
  yield return new WaitForSeconds(.7f);Verify(IsOpen&&canvas.enabled&&!game.gameCamera.enabled&&stage.view.enabled&&!game.CanPlay,"Lobby did not suspend gameplay / activate menu camera");VerifyExclusiveScreen(true);Verify(!safeRoot.GetComponentsInChildren<LobbyButton>(true).Any(b=>b.transform.parent==safeRoot&&RemovedHomeButton(b)),"Removed home buttons still exist");yield return VerifyStalePresentation();VerifyPageRays();yield return Shot("lobby-home");
  var skin=stage.spirit.GetComponentInChildren<SkinnedMeshRenderer>();float pose=skin.GetBlendShapeWeight(0)+skin.GetBlendShapeWeight(1);yield return new WaitForSeconds(.21f);Verify(Mathf.Abs(pose-skin.GetBlendShapeWeight(0)-skin.GetBlendShapeWeight(1))>.01f,"Lobby hero has no live blendshape animation");
  Press(LobbyAction.Greet);yield return new WaitForSeconds(.2f);Verify(stage.spirit.Find("Reference visual").localPosition.y>.08f,"Hero tap has no reaction");
  var menus=new[]{LobbyAction.Events,LobbyAction.Tasks,LobbyAction.Shop,LobbyAction.Collection,LobbyAction.Stats,LobbyAction.Skins,LobbyAction.Settings,LobbyAction.Profile,LobbyAction.Crystals,LobbyAction.Resonance};
  foreach(var action in menus){Press(action);yield return new WaitForSeconds(.2f);Verify(Page!="","Navigation did not open page "+action);VerifyPageRays();Press(LobbyAction.Close);yield return null;Verify(Page=="","Close did not return to home");}
  Press(LobbyAction.Gift);yield return null;Press(LobbyAction.ClaimGift);Verify(Profile.crystals==100&&Profile.resonance==1,"Gift currency not awarded");Click(LobbyAction.ClaimGift);Verify(Profile.crystals==100&&Profile.resonance==1,"Daily reward was granted twice");yield return Shot("lobby-daily-reward");ClosePopup();
  Press(LobbyAction.Shop);yield return null;Press(LobbyAction.BuySkin,1);Verify(Profile.crystals==100&&Profile.selectedSkin==0,"Insufficient-funds purchase mutated balance or skin");Profile.crystals=300;Press(LobbyAction.BuySkin,1);Verify(Profile.crystals==100&&Profile.selectedSkin==1&&(Profile.ownedSkins&2)!=0,"Skin purchase/equip failed");Click(LobbyAction.BuySkin,1);Verify(Profile.crystals==100,"Owned skin charged twice");yield return Shot("lobby-skins");int oldResonance=Profile.resonance;Press(LobbyAction.BuySkin,3);Verify(Profile.resonance==oldResonance&&Profile.selectedSkin==1,"Insufficient resonance bought a skin");Profile.resonance=3;Press(LobbyAction.BuySkin,3);Verify(Profile.resonance==0&&Profile.selectedSkin==3,"Resonance skin purchase failed");Click(LobbyAction.BuySkin,3);Verify(Profile.resonance==0,"Owned resonance skin charged twice");ClosePopup();
  Press(LobbyAction.Profile);yield return null;nameInput.text="Искра123";Press(LobbyAction.SaveName);Verify(Profile.playerName=="Искра123"&&nameLabel.text=="Искра123","Profile name button failed");
  Press(LobbyAction.Settings);yield return null;var sliders=popupRoot.GetComponentsInChildren<Slider>();Verify(sliders.Length==2,"Missing audio sliders");sliders[0].value=.23f;sliders[1].value=.12f;Canvas.ForceUpdateCanvases();foreach(var slider in sliders){Verify(slider.fillRect.rect.width<=360.1f&&slider.fillRect.rect.height<=6.1f&&slider.handleRect.rect.height<=25.1f,"Audio slider overflows its track");}Verify(Mathf.Abs(Profile.music-.23f)<.001f&&Mathf.Abs(Profile.sound-.12f)<.001f&&Mathf.Abs(ambience.volume-.23f)<.001f,"Settings sliders are disconnected");Press(LobbyAction.ToggleJumpSound);yield return null;Verify(!Profile.jumpSound&&Mathf.Abs(Profile.sound-.12f)<.001f&&Mathf.Abs(Profile.music-.23f)<.001f,"Jump mute altered other audio settings");Press(LobbyAction.ToggleJumpSound);Verify(Profile.jumpSound,"Jump sound cannot be re-enabled");Press(LobbyAction.ToggleMotion);yield return null;Verify(Profile.reducedMotion&&stage.reducedMotion,"Reduced-motion setting not applied");yield return Shot("lobby-settings");Press(LobbyAction.ToggleMotion);ClosePopup();
  Profile.wins=1;Profile.claimedTasks=0;int before=Profile.crystals;Press(LobbyAction.Tasks);yield return null;Press(LobbyAction.ClaimTask,0);Verify(Profile.crystals==before+50,"Task reward failed");Click(LobbyAction.ClaimTask,0);Verify(Profile.crystals==before+50,"Task reward duplicated");ClosePopup();completed=1;Profile.claimedAchievements=0;before=Profile.crystals;ShowPage("Достижения");yield return null;Press(LobbyAction.ClaimAchievement,0);Verify(Profile.crystals==before+100,"Achievement reward failed");Click(LobbyAction.ClaimAchievement,0);Verify(Profile.crystals==before+100,"Achievement reward duplicated");ClosePopup();
  game.VerificationUnlock(3);Click(LobbyAction.Levels);yield return null;VerifyPageRays();Verify(!popupRoot.GetComponentsInChildren<LobbyButton>().First(b=>b.action==LobbyAction.SelectLevel&&b.value==3).GetComponent<Button>().interactable,"Locked level is interactable");Click(LobbyAction.SelectLevel,5);Verify(IsOpen&&Page=="Уровни","Locked level was entered");yield return Shot("lobby-levels");Press(LobbyAction.NextPage);Verify(levelPage==1,"Level pagination forward failed");Press(LobbyAction.PreviousPage);Verify(levelPage==0,"Level pagination backward failed");ClosePopup();game.VerificationUnlock(100);
  Press(LobbyAction.Play);yield return null;Verify(!IsOpen&&game.gameCamera.enabled&&game.CurrentLevel.id==100,"Play did not start unlocked campaign level");VerifyExclusiveScreen(false);game.RequestUI(CampaignUICommand.Home);yield return null;Verify(IsOpen,"In-game Home button did not return to lobby");VerifyExclusiveScreen(true);
  Press(LobbyAction.Events);yield return null;Press(LobbyAction.StartChallenge);yield return null;Verify(Mode==LobbyMode.Challenge&&!IsOpen&&ModeTarget==game.CurrentLevel.optimalTurns+2,"Challenge did not load its real level and turn objective");yield return game.PlayWitnessForLobbyTest();Verify(game.Victorious,"Challenge is not playable to victory");int challengeCrystals=Profile.crystals,challengeResonance=Profile.resonance;RecordVictory(game.CurrentLevel.id,game.Turns,3);Verify(Profile.crystals==challengeCrystals&&Profile.resonance==challengeResonance,"Daily challenge awarded a duplicate reward");modeWins++;game.RequestUI(CampaignUICommand.Primary);yield return null;Verify(IsOpen,"Challenge completion did not return home");
  Click(LobbyAction.Endless);yield return null;Press(LobbyAction.StartEndless);yield return null;int first=game.CurrentLevel.id;yield return game.PlayWitnessForLobbyTest();Verify(game.Victorious&&EndlessCount==1,"Endless did not record a won round");modeWins++;game.RequestUI(CampaignUICommand.Primary);yield return null;Verify(!IsOpen&&game.CurrentLevel.id!=first&&!game.Victorious,"Endless next did not load another map");game.RequestUI(CampaignUICommand.Home);yield return null;
  Verify(game.gameCamera.transform.position==cameraPosition&&Quaternion.Angle(game.gameCamera.transform.rotation,cameraRotation)<.001f&&Mathf.Abs(game.gameCamera.fieldOfView-22)<.001f,"Lobby changed gameplay camera/FOV");
  var decoded=JsonUtility.FromJson<PulseProfile>(JsonUtility.ToJson(Profile));Verify(decoded.playerName==Profile.playerName&&decoded.crystals==Profile.crystals&&decoded.ownedSkins==Profile.ownedSkins&&decoded.giftDay==Profile.giftDay,"Profile save format does not round-trip");
  Verify(PlayerPrefs.GetString("PulseLobby.Profile.v1","")==persisted,"Verification modified player profile");Verify(PlayerPrefs.GetInt("PulseCampaign.Variety2.Current",1)+"/"+PlayerPrefs.GetInt("PulseCampaign.Variety2.Unlocked",1)==savedProgress,"Verification modified campaign progress");
  Profile=PulseProfile.Load(true);game.VerificationUnlock(1);stage.ApplySkin(0);RefreshHeader();Mode=LobbyMode.Campaign;yield return Shot("lobby-home-final");
  var report=new LobbyReport{success=lobbyFailures.Count==0,checks=lobbyChecks,buttonRaycasts=lobbyRays,animatedModeVictories=modeWins,failures=lobbyFailures.ToArray()};System.IO.File.WriteAllText(System.IO.Path.GetFullPath(Application.dataPath+"/../../lobby-verification.json"),JsonUtility.ToJson(report,true));Debug.Log("LOBBY_VERIFIED "+lobbyChecks+" checks / "+lobbyRays+" UI rays / success="+report.success);Application.Quit(report.success?0:1);
 }
}
